In [2]:
pip install sympy

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [sympy]32m1/2 [sympy]
Note: you may need to restart the kernel to use updated packages.


In [5]:
import sympy as sp

# Symbols
nA, nB, L0 = sp.symbols('n_A n_B L_0', positive=True)

# Total moles and mole fractions
n = nA + nB
xA = nA / n
xB = nB / n

# # Excess Gibbs energy for v = 0
# # G_ex = n * xA * xB * L0
# # Equivalent form:
# G = (nA * nB / n) * L0

# # first partial derivatives (chemical potentials)
# muA = sp.simplify(sp.diff(G, nA))
# muB = sp.simplify(sp.diff(G, nB))

# # second derivatives (Hessian)
# G_AA = sp.simplify(sp.diff(muA, nA))
# G_BB = sp.simplify(sp.diff(muB, nB))
# G_AB = sp.simplify(sp.diff(muA, nB))  # = G_BA

# # show results
# sp.pretty_print(muA)
# sp.pretty_print(muB)
# sp.pretty_print(G_AA)
# sp.pretty_print(G_BB)
# sp.pretty_print(G_AB)

In [17]:
# xA, xB, L0 = sp.symbols('xA xB L0', positive=True)
# g = xA * xB * L0  # simple RK with one parameter just as an example
# #xB = 1 - xA  # if treating as dependent

# gA = sp.diff(g, xA)
# gB = sp.diff(g, xB)  # if treating xA,xB independent

# gAA = sp.diff(gA, xA)
# gAB = sp.diff(gA, xB)
# gBB = sp.diff(gB, xB)

# # using xA,xB,g,gA,gB
# muA = g + gA - (xA*gA + xB*gB)
# muB = g + gB - (xA*gA + xB*gB)

# dmuA_dxA = sp.diff(muA, xA)
# dmuA_dxB = sp.diff(muA, xB)
# dmuB_dxA = sp.diff(muB, xA)
# dmuB_dxB = sp.diff(muB, xB)

# # show results
# sp.pretty_print(muA)
# sp.pretty_print(muB)
# sp.pretty_print(gAA)
# sp.pretty_print(gBB)
# sp.pretty_print(gAB)
# sp.pretty_print(dmuA_dxA)
# sp.pretty_print(dmuA_dxB)
# sp.pretty_print(dmuB_dxA)
# sp.pretty_print(dmuB_dxB)

In [26]:
# xA, xB, L0 = sp.symbols('xA xB L0', positive=True)
# xA = 1 - xB  # if treating as dependent
# g = xA * xB * L0

# dg_dxB = sp.diff(g, xB)
# d2g_dxB2 = sp.diff(dg_dxB, xB)
# sp.simplify(d2g_dxB2)   
# sp.pretty_print(d2g_dxB2)

In [ ]:
# import sympy as sp

# # symbols
# xA, xB, L0, L1 = sp.symbols('xA xB L0 L1', real=True)

# # first-order Redlich–Kister excess Gibbs energy
# g_ex = xA * xB * (L0 + L1 * (xA - xB))

# # first derivatives
# gA = sp.diff(g_ex, xA)
# gB = sp.diff(g_ex, xB)

# # second derivatives
# gAA = sp.simplify(sp.diff(gA, xA))      # d²g/dxA²
# gAB = sp.simplify(sp.diff(gA, xB))      # d²g/dxAdxB
# gBA = sp.simplify(sp.diff(gB, xA))      # d²g/dxBdxA
# gBB = sp.simplify(sp.diff(gB, xB))      # d²g/dxB²

# # show results
# sp.pretty_print(gAA)
# sp.pretty_print(gBB)
# sp.pretty_print(gAB)
# sp.pretty_print(gBA)

2⋅L₁⋅xB
-2⋅L₁⋅xA
L₀ + 2⋅L₁⋅xA - 2⋅L₁⋅xB
L₀ + 2⋅L₁⋅xA - 2⋅L₁⋅xB


In [ ]:
# import sympy as sp

# # symbols
# xB, L0, L1 = sp.symbols('xB L0 L1', real=True)
# xA = 1 - xB                # enforce binary constraint

# # first-order RK excess Gibbs energy, in terms of xB only
# g_ex = xA * xB * (L0 + L1 * (xA - xB))

# # first and second derivative wrt composition xA
# dg_dxB   = sp.diff(g_ex, xB)
# d2g_dxB2 = sp.simplify(sp.diff(dg_dxB, xB))

# sp.pretty_print(d2g_dxB2)


-2⋅L₀ + 12⋅L₁⋅xB - 6⋅L₁


In [ ]:

# # symbols
# xA, L0, L1 = sp.symbols('xA L0 L1', real=True)
# xB = 1 - xA                      # enforce binary constraint

# # first-order RK excess Gibbs energy, in terms of xA only
# g_ex = xA * xB * (L0 + L1 * (xA - xB))   # xB = 1-xA already

# # first and second derivative wrt composition xA
# dg_dxA   = sp.diff(g_ex, xA)
# d2g_dxA2 = sp.simplify(sp.diff(dg_dxA, xA))

# sp.pretty_print(d2g_dxA2)


-2⋅L₀ - 12⋅L₁⋅xA + 6⋅L₁


In [46]:
import sympy as sp
#sp.init_printing(wrap_line=False)

# composition variables (independent)
xA, xB = sp.symbols('xA xB', real=True)

# enforce ternary constraint: xA + xB + xC = 1
xC = 1 - xA - xB

LA0, LB0, LC0 = sp.symbols('LA0 LB0 LC0', real=True)
g_ex_ter = xA * xB * xC * (LA0 * xA + LB0 * xB + LC0 * xC)

sp.pretty_print(g_ex_ter)

# get the 2×2 constrained Hessian:
gA = sp.diff(g_ex_ter, xA)
gB = sp.diff(g_ex_ter, xB)
gAA = sp.simplify(sp.diff(gA, xA))
gAB = sp.simplify(sp.diff(gA, xB))
gBA = sp.simplify(sp.diff(gB, xA))
gBB = sp.simplify(sp.diff(gB, xB))

sp.pretty_print(gAA)
sp.pretty_print(gBB)
sp.pretty_print(gAB)
sp.pretty_print(gBA)



xA⋅xB⋅(-xA - xB + 1)⋅(LA₀⋅xA + LB₀⋅xB + LC₀⋅(-xA - xB + 1))
2⋅xB⋅(-LA₀⋅xA - LB₀⋅xB + LC₀⋅(xA + xB - 1) - xA⋅(LA₀ - LC₀) - (LA₀ - LC₀)⋅(xA + xB - 1))
2⋅xA⋅(-LA₀⋅xA - LB₀⋅xB + LC₀⋅(xA + xB - 1) - xB⋅(LB₀ - LC₀) - (LB₀ - LC₀)⋅(xA + xB - 1))
          2                                                  2                      2                                    2                 
- 3⋅LA₀⋅xA  - 4⋅LA₀⋅xA⋅xB + 2⋅LA₀⋅xA - 4⋅LB₀⋅xA⋅xB - 3⋅LB₀⋅xB  + 2⋅LB₀⋅xB + 3⋅LC₀⋅xA  + 8⋅LC₀⋅xA⋅xB - 4⋅LC₀⋅xA + 3⋅LC₀⋅xB  - 4⋅LC₀⋅xB + LC₀
          2                                                  2                      2                                    2                 
- 3⋅LA₀⋅xA  - 4⋅LA₀⋅xA⋅xB + 2⋅LA₀⋅xA - 4⋅LB₀⋅xA⋅xB - 3⋅LB₀⋅xB  + 2⋅LB₀⋅xB + 3⋅LC₀⋅xA  + 8⋅LC₀⋅xA⋅xB - 4⋅LC₀⋅xA + 3⋅LC₀⋅xB  - 4⋅LC₀⋅xB + LC₀


In [ ]:
import numpy as np

# constants
R = 8.314
T = 1000.0  # K

# Creating a fake RKMP "database":
#   Lcoeff[(i,j)] = [L0, L1, L2, ...]  for that pair
#   Units: J/mol
Lcoeff = {
    (0, 1): [ 2000.0,  -500.0,  100.0],   # L01(Δ) = 2000 - 500 Δ + 100 Δ^2
    (0, 2): [ 1500.0,   200.0        ], # L02(Δ) = 1500 + 200 Δ
    (1, 2): [ 3000.0, -1000.0,  250.0],   # L12(Δ) = 3000 - 1000 Δ + 250 Δ^2
}

# Helpers for L(Δ), L'(Δ), L''(Δ)
def L_poly(delta, coeffs):
    # sum_v coeffs[v] * delta**v
    out = 0.0
    p = 1.0
    for c in coeffs:
        out += c * p
        p *= delta
    return out

def L_prime(delta, coeffs):
    # d/dΔ of sum_v L_v Δ^v = sum_{v>=1} v L_v Δ^(v-1)
    out = 0.0
    for v in range(1, len(coeffs)):
        out += v * coeffs[v] * (delta ** (v - 1))
    return out

def L_second(delta, coeffs):
    # d^2/dΔ^2 = sum_{v>=2} v(v-1) L_v Δ^(v-2)
    out = 0.0
    for v in range(2, len(coeffs)):
        out += v * (v - 1) * coeffs[v] * (delta ** (v - 2))
    return out

# Implement g(x)
def g(x):
    x = np.asarray(x, dtype=float)
    if np.any(x <= 0.0) or abs(np.sum(x) - 1.0) > 1e-12:
        return np.nan

    # ideal mixing term
    gid = R * T * np.sum(x * np.log(x))

    # RKMP pair excess term
    gex = 0.0
    for (i, j), coeffs in Lcoeff.items():
        delta = x[i] - x[j]
        L = L_poly(delta, coeffs)
        gex += x[i] * x[j] * L

    return gid + gex

# Analytic unconstrained Hessian H_ij = ∂²g/∂x_i∂x_j
def H_unconstrained(x):
    x = np.asarray(x, dtype=float)
    C = len(x)
    H = np.zeros((C, C), dtype=float)

    # ideal term: only diagonal
    for i in range(C):
        H[i, i] += R * T / x[i]
    # no off-diagaonal ideal contributions since ∂²/∂x_i∂x_j of ideal term is zero for i≠j   

    # pair contributions
    for (i, j), coeffs in Lcoeff.items():
        delta = x[i] - x[j]
        L   = L_poly(delta, coeffs)
        Lp  = L_prime(delta, coeffs)
        Lpp = L_second(delta, coeffs)

        # from derived formulas for φ_ij = x_i x_j L(Δ):
        H[i, i] +=  2.0 * x[j] * Lp + x[i] * x[j] * Lpp
        H[j, j] += -2.0 * x[i] * Lp + x[i] * x[j] * Lpp

        Hij = L + delta * Lp - x[i] * x[j] * Lpp
        H[i, j] += Hij
        H[j, i] += Hij

    return H

# Constrained Hessian via reference component r (independent vars are all indices except r)
def H_constrained(x, r):
    H = H_unconstrained(x)
    C = len(x)
    idx = [i for i in range(C) if i != r]  # independent indices

    Ht = np.zeros((C - 1, C - 1), dtype=float)
    for a, ia in enumerate(idx):
        for b, ib in enumerate(idx):
            Ht[a, b] = H[ia, ib] - H[ia, r] - H[r, ib] + H[r, r]
    return Ht, idx

# Finite-difference constrained Hessian directly from g(x) by perturbing independent components and adjusting x_r
def FD_H_constrained(x0, r, delta):
    x0 = np.asarray(x0, dtype=float)
    Ht, idx = H_constrained(x0, r)
    m = len(idx)
    Hfd = np.zeros((m, m), dtype=float)

    g0 = g(x0)

    # diagonal entries
    for a, ia in enumerate(idx):
        xp = x0.copy()
        xm = x0.copy()

        xp[ia] += delta
        xp[r]  -= delta

        xm[ia] -= delta
        xm[r]  += delta

        Hfd[a, a] = (g(xp) - 2.0 * g0 + g(xm)) / (delta ** 2)

    # off-diagonal entries
    for a, ia in enumerate(idx):
        for b, ib in enumerate(idx):
            if b <= a:
                continue

            xpp = x0.copy()
            xpm = x0.copy()
            xmp = x0.copy()
            xmm = x0.copy()

            # ++
            xpp[ia] += delta; xpp[ib] += delta; xpp[r] -= 2.0 * delta
            # +-
            xpm[ia] += delta; xpm[ib] -= delta; xpm[r] -= (delta - delta)  # = 0
            # -+
            xmp[ia] -= delta; xmp[ib] += delta; xmp[r] -= (-delta + delta) # = 0
            # --
            xmm[ia] -= delta; xmm[ib] -= delta; xmm[r] += 2.0 * delta

            H_ab = (g(xpp) - g(xpm) - g(xmp) + g(xmm)) / (4.0 * delta ** 2)
            Hfd[a, b] = H_ab
            Hfd[b, a] = H_ab

    return Hfd, Ht, idx

# RUN THE TEST
x0 = np.array([0.40, 0.35, 0.25])  # must sum to 1 and all > 0
r  = 0                              # choose reference as the largest component (safer)
print("Base g(x0) =", g(x0))

for delta in [1e-2, 1e-3, 1e-4, 1e-5, 1e-6]:
    Hfd, Ht, idx = FD_H_constrained(x0, r, delta)

    rel_err = np.linalg.norm(Hfd - Ht) / max(1.0, np.linalg.norm(Ht))
    print(f"\nδ = {delta:g}, relative error = {rel_err:.3e}")
    print("independent indices =", idx)
    print("analytic constrained Hessian:\n", Ht)
    print("FD constrained Hessian:\n", Hfd)


Base g(x0) = -8300.002937587085

δ = 0.01, relative error = 2.433e-04
independent indices = [1, 2]
analytic constrained Hessian:
 [[40467.53571429 19851.        ]
 [19851.         51254.75      ]]
FD constrained Hessian:
 [[40472.85429129 19859.62908869]
 [19859.62908869 51265.78959284]]

δ = 0.001, relative error = 2.431e-06
independent indices = [1, 2]
analytic constrained Hessian:
 [[40467.53571429 19851.        ]
 [19851.         51254.75      ]]
FD constrained Hessian:
 [[40467.58888398 19851.08620511]
 [19851.08620511 51254.86033467]]

δ = 0.0001, relative error = 2.442e-08
independent indices = [1, 2]
analytic constrained Hessian:
 [[40467.53571429 19851.        ]
 [19851.         51254.75      ]]
FD constrained Hessian:
 [[40467.53638249 19851.00093407]
 [19851.00093407 51254.75090608]]

δ = 1e-05, relative error = 3.912e-07
independent indices = [1, 2]
analytic constrained Hessian:
 [[40467.53571429 19851.        ]
 [19851.         51254.75      ]]
FD constrained Hessian:
 [[4